<Project Sdk="Microsoft.NET.Sdk.WebAssembly">
	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
		<OverrideHtmlAssetPlaceholders>true</OverrideHtmlAssetPlaceholders>
		<CompressionEnabled>false</CompressionEnabled>
	</PropertyGroup>
	<ItemGroup>
		<ProjectReference Include="..\SpawnDev.SpawnJS\SpawnDev.SpawnJS.csproj" />
	</ItemGroup>

	<ItemGroup>
		<StaticWebAssetFingerprintPattern Include="JS" Pattern="*.js" Expression="#[.{fingerprint}]!" />
	</ItemGroup>
</Project>
