
using SpawnDev.SpawnJS;
using SpawnDev.SpawnJS.JSObjects;
namespace SpawnDev.SpawnJS.JSObjects
{
    /// <summary>
    /// The GPUCompilationInfo interface of the WebGPU API represents an array of GPUCompilationMessage objects generated by the GPU shader module compiler to help diagnose problems with shader code.<br/>
    /// GPUCompilationInfo is accessed via GPUShaderModule.getCompilationInfo().<br/>
    /// https://developer.mozilla.org/en-US/docs/Web/API/GPUCompilationInfo
    /// </summary>
    public class GPUCompilationInfo : SpawnJSObject
    {
        /// <inheritdoc/>
        public GPUCompilationInfo(SpawnJSObjectReference _ref) : base(_ref) { }
        /// <summary>
        /// An array of GPUCompilationMessage objects, each one containing the details of an individual shader compilation message. Messages can be informational, warnings, or errors.
        /// </summary>
        public GPUCompilationMessage[] Messages => JSRef!.Get<GPUCompilationMessage[]>("messages");
    }
}
